export type Word = {
  module?: string;
  spanish: string;
  english?: string;
  romaji?: string;
  furigana: string;
  kanji: string;
};
export type Words = {
  [key: string]: Word[];

  vocabulary: Word[];
  verbs: Word[];
};

export default {
  languages: [
    { module: '1', spanish: 'ingles', romaji: '', furigana: 'えいご', kanji: '' },
    // { module: '', spanish: '', romaji: '', furigana: '', kanji: '' },
    // { module: '', spanish: '', romaji: '', furigana: '', kanji: '' },
    // { module: '', spanish: '', romaji: '', furigana: '', kanji: '' },
    // { module: '', spanish: '', romaji: '', furigana: '', kanji: '' },
    // { module: '', spanish: '', romaji: '', furigana: '', kanji: '' },
  ],
  vocabulary: [
    { module: '1', spanish: 'lapicera', romaji: 'bôrupen', furigana: 'ボウルペン', kanji: '' },
    { module: '1', spanish: 'lapiz de mina', romaji: 'shâbupen', furigana: '', kanji: '' },
    { module: '1', spanish: 'lapiz', romaji: 'enpitsu', furigana: 'えんぴつ', kanji: '' },
    { module: '1', spanish: 'saca puntas', romaji: 'enpitsukezuri', furigana: 'えんぴつけずり', kanji: '鉛筆削り' },
    { module: '1', spanish: 'liquid paper', romaji: 'inkukeshi', furigana: '', kanji: '' },
    { module: '1', spanish: '', romaji: 'keshigomu', furigana: '', kanji: '' },
    { module: '1', spanish: 'cartuchera', romaji: 'fudebako', furigana: '', kanji: '' },
    { module: '1', spanish: 'bolso, cartera', romaji: 'kaban', furigana: '', kanji: '' },
    { module: '1', spanish: 'carpeta', romaji: 'baindâ', furigana: '', kanji: '' },
    { module: 'general', spanish: 'pelicula', furigana: 'えいが', kanji: '' },
    { module: 'general', spanish: 'todos los dias', romaji: '', furigana: 'まいにち', kanji: '' },
    { module: 'general', spanish: 'diario', romaji: '', furigana: 'しんぶん', kanji: '' },
    { module: '', spanish: 'beisbol', romaji: '', furigana: 'やきゅう', kanji: '' },
    { module: '', spanish: 'agua', romaji: '', furigana: 'みず', kanji: '' },
    { module: '', spanish: 'yo femenino', romaji: '', furigana: 'あたし', kanji: '' },
    { module: '', spanish: 'casa', romaji: '', furigana: 'いえ', kanji: '' },
    { module: '', spanish: 'hogar', romaji: '', furigana: 'うち', kanji: '' },
    { module: '', spanish: 'vecino', romaji: '', furigana: 'となりのひと', kanji: '' },
    { module: '', spanish: 'mi familia', romaji: '', furigana: 'かろく', kanji: '' },
    { module: '', spanish: 'nada', romaji: '', furigana: 'なにも', kanji: '' },
    { module: '', spanish: 'este año', romaji: '', furigana: 'ことし', kanji: '' },
    { module: '', spanish: 'año que viene', romaji: '', furigana: 'らいねん', kanji: '' },
    { module: '', spanish: 'año pasado', romaji: '', furigana: 'きょねん', kanji: '' },
    { module: '', spanish: 'nos vemos', romaji: '', furigana: 'またね', kanji: '' },
    { module: '', spanish: 'despues de', romaji: '', furigana: 'のあとで', kanji: '' },
    { module: '', spanish: 'solamente', romaji: '', furigana: 'たけ', kanji: '' },
    { module: '', spanish: 'beisbol', romaji: '', furigana: 'やきゅう', kanji: '' },
    { module: '', spanish: 'fin de semana', romaji: '', furigana: 'しゅうまつ', kanji: '' },
    { module: '', spanish: 'año', romaji: '', furigana: 'ねん', kanji: '' },
    { module: '', spanish: 'cumpleaños', romaji: '', furigana: 'おたんじょうび', kanji: '' },
    { module: '', spanish: 'cuando', romaji: '', furigana: 'いつ', kanji: '' },
    { module: '', spanish: 'amigo', romaji: '', furigana: 'ともだち', kanji: '' },
    // { module: '', spanish: '', romaji: '', furigana: '', kanji: '' },
    // { module: '', spanish: '', romaji: '', furigana: '', kanji: '' },
    // { module: '', spanish: '', romaji: '', furigana: '', kanji: '' },
    // { module: '', spanish: '', romaji: '', furigana: '', kanji: '' },
    // { module: '', spanish: '', romaji: '', furigana: '', kanji: '' },
  ],
  verbs: [
    { module: '1', spanish: 'comer', romaji: '', furigana: 'たべます', kanji: '' },
    { module: '1', spanish: 'tomar', romaji: '', furigana: 'のみます', kanji: '' },
    { module: '1', spanish: 'estudiar', romaji: '', furigana: 'ベんきょうします', kanji: '' },
    { module: '1', spanish: 'hacer', romaji: '', furigana: 'します', kanji: '' },
    { module: '1', spanish: 'leer', romaji: '', furigana: 'よみます', kanji: '' },
    { module: '1', spanish: 'mirar', romaji: '', furigana: 'みます', kanji: '' },
    { module: '1', spanish: 'escuchar', romaji: '', furigana: 'ききます', kanji: '' },
    { module: '2', spanish: 'ir', romaji: '', furigana: 'いきます', kanji: '行きます' },
    { module: '2', spanish: 'venir', romaji: '', furigana: 'きます', kanji: '来ます' },
    { module: '2', spanish: 'volver', romaji: '', furigana: 'かえります', kanji: '' },
    { module: '', spanish: 'to meet', romaji: '', furigana: 'あいます', kanji: '会います' },
    { module: '', spanish: 'to take / to steal', romaji: '', furigana: 'とります', kanji: '摂ります' },
    { module: '', spanish: 'to write', romaji: '', furigana: 'かきます', kanji: '' },
    { module: '', spanish: 'to work', romaji: '', furigana: 'はたらきます', kanji: '' },
    { module: '', spanish: 'despertar', romaji: '', furigana: 'おきます', kanji: '' },
    { module: '', spanish: 'dormir', romaji: '', furigana: 'ねます', kanji: '' },
    { module: '', spanish: 'dar', romaji: '', furigana: 'あげます', kanji: '' },
    { module: '', spanish: 'recibir', romaji: '', furigana: 'もらいます', kanji: '' },
    { module: '', spanish: 'enseñar', romaji: '', furigana: 'おしえます', kanji: '' },
    { module: '', spanish: 'aprender', romaji: '', furigana: 'ならいます', kanji: '' },
    { module: '', spanish: 'prestar', romaji: '', furigana: 'かします', kanji: '' },
    { module: '', spanish: 'tomar prestado', romaji: '', furigana: 'かります', kanji: '' },
    { module: '', spanish: 'hablar', romaji: '', furigana: 'はなします', kanji: '' },
    { module: '', spanish: 'descansar / faltar', romaji: '', furigana: 'やすみます', kanji: '' },
    { module: '', spanish: 'comprar', romaji: '', furigana: 'かいます', kanji: '買います' },
    // { module: '', spanish: '', romaji: '', furigana: '', kanji: '' },
    // { module: '', spanish: '', romaji: '', furigana: '', kanji: '' },
    // { module: '', spanish: '', romaji: '', furigana: '', kanji: '' },
  ],
  daysOfWeek: [
    { module: '', spanish: 'domingo', furigana: 'にちようび', kanji: '日曜日' },
    { module: '', spanish: 'lunes', furigana: 'げすようび', kanji: '月曜日' },
    { module: '', spanish: 'martes', furigana: 'かようび', kanji: '火曜日' },
    { module: '', spanish: 'miercoles', furigana: 'すいようび', kanji: '水曜日' },
    { module: '', spanish: 'jueves', furigana: 'もくようび', kanji: '木曜日' },
    { module: '', spanish: 'viernes', furigana: 'きんようび', kanji: '金曜日' },
    { module: '', spanish: 'sabado', furigana: 'どようび', kanji: '土曜日' },
  ],
  adjetives: [
    { spanish: 'grande', furigana: 'おおきい', kanji: '' },
    { spanish: 'chiquito', furigana: 'ちいさい', kanji: '' },
    { spanish: 'rico (sabor)', furigana: 'おいしい', kanji: '' },
    { spanish: 'feo (sabor)', furigana: 'まずい', kanji: '' },
    { spanish: 'dificil', furigana: 'むずかしい', kanji: '' },
    { spanish: 'facil', english: 'easy, kind', furigana: 'やさしい', kanji: '' },
    { spanish: 'caliente', english: 'hot', furigana: 'あつい', kanji: '' },
    { spanish: 'frio (de clima)', furigana: 'さむい', kanji: '' },
    { spanish: 'frio (tangible)', furigana: 'つめたい', kanji: '' },
    { spanish: 'largo (tiempo y espacio)', furigana: 'ながい', kanji: '長い' },
    { spanish: 'corto (tiempo y espacio)', english: 'short', furigana: 'みじかい', kanji: '' },
    { spanish: 'divertido', furigana: 'たのしい', kanji: '' },
    { spanish: 'aburrido', furigana: 'つまらない', kanji: '' },
    { spanish: 'interesante', furigana: 'おもしろい', kanji: '' },
    { spanish: 'hermoso (hombres)', english: 'handson', furigana: 'ハンサムな', kanji: '' },
    { spanish: 'hermoso o limpio (mujeres, paisajes, lugares)', furigana: 'きれいな', kanji: '' },
    { spanish: 'comodo, practico', furigana: 'べんりな', kanji: '' },
    { spanish: 'incomodo, impractico', furigana: 'ふべんな', kanji: '' },
    { spanish: 'amable', furigana: 'しんせつな', kanji: '' },
    { spanish: 'importante, vital', furigana: 'だいじな', kanji: '' },
    { spanish: 'tener tiempo libre, estar libre, no tener nada q hacer, estar al pedo', furigana: 'ひまな', kanji: '' },
    { spanish: 'saludable, que tiene mucha energia', furigana: 'げんきな', kanji: '' },
    { spanish: 'con sueño', english: 'sleepy', furigana: 'ねむい', kanji: '' },
    { spanish: 'adorable, lindo', furigana: 'すてきな', kanji: '' },
    { spanish: 'nuevo', furigana: 'あたらしい', kanji: '' },
    { spanish: 'viejo', furigana: 'ふるい', kanji: '' },
    { spanish: 'malo', furigana: 'わるい', kanji: '' },
    { spanish: 'barato', furigana: 'やすい', kanji: '' },
    { spanish: 'bajo', furigana: 'ひくい', kanji: '' },
    { spanish: 'ocupado', furigana: 'いそがしい', kanji: '' },
    { spanish: 'bullilloso, lugar con vida', english: 'busy', furigana: 'にぎやか', kanji: '' },
    { spanish: 'bueno, bien', furigana: 'いい', kanji: '' },
    // { module: '', spanish: '', romaji: '', furigana: '', kanji: '' },
    // { module: '', spanish: '', romaji: '', furigana: '', kanji: '' },
    // { module: '', spanish: '', romaji: '', furigana: '', kanji: '' },
    // { module: '', spanish: '', romaji: '', furigana: '', kanji: '' },
    // { module: '', spanish: '', romaji: '', furigana: '', kanji: '' },
  ],
} as Words;
