export type SpanishWord = { spanish: string };

export type EnglishWord = { english: string };

export type Word = ((SpanishWord & Partial<EnglishWord>) | (EnglishWord & Partial<SpanishWord>)) & {
  module?: string;
  furigana: string;
  kanji?: string;
};

export type Words = {
  languages: Word[];
  vocabulary: Word[];
  verbs: Word[];
  daysOfWeek: Word[];
  adjetives: Word[];
  colors: Word[];
  counters: Word[];
};

const words: Words = {
  languages: [
    { module: '1', spanish: 'ingles', furigana: 'えいご', kanji: '' },
    { spanish: 'ingles', furigana: 'えいご', kanji: '' },
    // { module: '', spanish: '',  furigana: '', kanji: '' },
    // { module: '', spanish: '',  furigana: '', kanji: '' },
    // { module: '', spanish: '',  furigana: '', kanji: '' },
    // { module: '', spanish: '',  furigana: '', kanji: '' },
    // { module: '', spanish: '',  furigana: '', kanji: '' },
  ],
  vocabulary: [
    { module: '1', spanish: 'lapicera', furigana: 'ボウルペン', kanji: '' },
    { module: '1', spanish: 'lapiz', furigana: 'えんぴつ', kanji: '' },
    { module: '1', spanish: 'saca puntas', furigana: 'えんぴつけずり', kanji: '鉛筆削り' },
    { module: '1', spanish: 'bolso, cartera', furigana: 'かばん', kanji: '' },
    { module: 'general', spanish: 'pelicula', furigana: 'えいが', kanji: '' },
    { module: 'general', spanish: 'todos los dias', furigana: 'まいにち', kanji: '' },
    { module: 'general', spanish: 'diario', furigana: 'しんぶん', kanji: '' },
    { module: '', spanish: 'beisbol', furigana: 'やきゅう', kanji: '' },
    { module: '', spanish: 'agua', furigana: 'みず', kanji: '水' },
    { module: '', spanish: 'yo', furigana: 'わたし', kanji: '私' },
    { module: '', spanish: 'yo femenino', furigana: 'あたし', kanji: '' },
    { module: '', spanish: 'el', english: 'him', furigana: 'かれ', kanji: '彼' },
    { module: '', spanish: 'casa', furigana: 'いえ', kanji: '' },
    { module: '', spanish: 'hogar', furigana: 'うち', kanji: '' },
    { module: '', spanish: 'vecino', furigana: 'となりのひと', kanji: '' },
    { module: '', spanish: 'mi familia', furigana: 'かぞく', kanji: '' },
    { module: '', spanish: 'nada/todo', english: 'nothing/everything', furigana: 'なにも', kanji: '' },
    { module: '', spanish: 'nadie/todos', english: 'nobory/everybody', furigana: 'だれも', kanji: '' },
    { spanish: 'en nigun lado/en todos lados', english: 'anywhere/everywhere', furigana: 'どこも' },
    { module: '', spanish: 'nunca/siempre', english: 'never/always', furigana: 'いつも', kanji: '' },
    { module: '', spanish: 'este año', furigana: 'ことし', kanji: '' },
    { module: '', spanish: 'año que viene', furigana: 'らいねん', kanji: '' },
    { module: '', spanish: 'año pasado', furigana: 'きょねん', kanji: '' },
    { module: '', spanish: 'nos vemos', furigana: 'またね', kanji: '' },
    { module: '', spanish: 'despues de', furigana: 'のあとで', kanji: '' },
    { module: '', spanish: 'solamente', furigana: 'たけ', kanji: '' },
    { module: '', spanish: 'beisbol', furigana: 'やきゅう', kanji: '' },
    { module: '', spanish: 'fin de semana', furigana: 'しゅうまつ', kanji: '' },
    { module: '', spanish: 'año', furigana: 'ねん', kanji: '' },
    { module: '', spanish: 'cumpleaños', furigana: 'おたんじょうび', kanji: '' },
    { module: '', spanish: 'cuando', furigana: 'いつ', kanji: '' },
    { module: '', spanish: 'amigo', furigana: 'ともだち', kanji: '' },
    { module: '', spanish: 'derecha', furigana: 'みぎ', kanji: '' },
    { module: '', spanish: 'izquierda', furigana: 'ひだり', kanji: '' },
    { module: '', spanish: 'enfrente', furigana: 'まえ', kanji: '' },
    { module: '', spanish: 'detras', furigana: 'うしろ', kanji: '' },
    { module: '', spanish: 'arriba', furigana: 'うえ', kanji: '上' },
    { module: '', spanish: 'debajo', furigana: 'した', kanji: '下' },
    { module: '', spanish: 'adentro', furigana: 'なか', kanji: '中' },
    { module: '', spanish: 'afuera', furigana: 'そと', kanji: '' },
    { module: '', spanish: 'cerca', furigana: 'そば', kanji: '' },
    { module: '', spanish: 'cerca', furigana: 'ちかく', kanji: '' },
    { module: '', spanish: 'al lado', furigana: 'となり', kanji: '' },
    { module: '', spanish: 'en medio de', furigana: 'あいだ', kanji: '' },
    { module: '', spanish: 'lluvia', furigana: 'あめ', kanji: '' },
    // { module: '', spanish: '',  furigana: '', kanji: '' },
    // { module: '', spanish: '',  furigana: '', kanji: '' },
    // { module: '', spanish: '',  furigana: '', kanji: '' },
    // { module: '', spanish: '',  furigana: '', kanji: '' },
    // { module: '', spanish: '',  furigana: '', kanji: '' },
  ],
  verbs: [
    { module: '1', spanish: 'comer', furigana: 'たべます', kanji: '' },
    { module: '1', spanish: 'tomar', furigana: 'のみます', kanji: '' },
    { module: '1', spanish: 'estudiar', furigana: 'ベんきょうします', kanji: '' },
    { module: '1', spanish: 'hacer', furigana: 'します', kanji: '' },
    { module: '1', spanish: 'leer', furigana: 'よみます', kanji: '' },
    { module: '1', spanish: 'mirar', furigana: 'みます', kanji: '' },
    { module: '1', spanish: 'escuchar', furigana: 'ききます', kanji: '' },
    { module: '2', spanish: 'ir', furigana: 'いきます', kanji: '行きます' },
    { module: '2', spanish: 'venir', furigana: 'きます', kanji: '来ます' },
    { module: '2', spanish: 'volver', furigana: 'かえります', kanji: '' },
    { module: '', spanish: 'to meet', furigana: 'あいます', kanji: '会います' },
    { module: '', spanish: 'to take / to steal', furigana: 'とります', kanji: '摂ります' },
    { module: '', spanish: 'to write', furigana: 'かきます', kanji: '' },
    { module: '', spanish: 'to work', furigana: 'はたらきます', kanji: '' },
    { module: '', spanish: 'despertar', furigana: 'おきます', kanji: '' },
    { module: '', spanish: 'dormir', furigana: 'ねます', kanji: '' },
    { module: '', spanish: 'dar', furigana: 'あげます', kanji: '' },
    { module: '', spanish: 'recibir', furigana: 'もらいます', kanji: '' },
    { module: '', spanish: 'enseñar', furigana: 'おしえます', kanji: '' },
    { module: '', spanish: 'aprender', furigana: 'ならいます', kanji: '' },
    { module: '', spanish: 'prestar', furigana: 'かします', kanji: '' },
    { module: '', spanish: 'tomar prestado', furigana: 'かります', kanji: '' },
    { module: '', spanish: 'hablar', furigana: 'はなします', kanji: '' },
    { module: '', spanish: 'descansar / faltar', furigana: 'やすみます', kanji: '' },
    { module: '', spanish: 'comprar', furigana: 'かいます', kanji: '買います' },
    { module: '', spanish: 'llover', furigana: 'あめがふります', kanji: '' },
    // { module: '', spanish: '',  furigana: '', kanji: '' },
    // { module: '', spanish: '',  furigana: '', kanji: '' },
    // { module: '', spanish: '',  furigana: '', kanji: '' },
  ],
  daysOfWeek: [
    { module: '', spanish: 'domingo', furigana: 'にちようび', kanji: '日曜日' },
    { module: '', spanish: 'lunes', furigana: 'げすようび', kanji: '月曜日' },
    { module: '', spanish: 'martes', furigana: 'かようび', kanji: '火曜日' },
    { module: '', spanish: 'miercoles', furigana: 'すいようび', kanji: '水曜日' },
    { module: '', spanish: 'jueves', furigana: 'もくようび', kanji: '木曜日' },
    { module: '', spanish: 'viernes', furigana: 'きんようび', kanji: '金曜日' },
    { module: '', spanish: 'sabado', furigana: 'どようび', kanji: '土曜日' },
  ],
  adjetives: [
    { spanish: 'grande', furigana: 'おおきい', kanji: '' },
    { spanish: 'chiquito', furigana: 'ちいさい', kanji: '' },
    { spanish: 'rico (sabor)', furigana: 'おいしい', kanji: '' },
    { spanish: 'feo (sabor)', furigana: 'まずい', kanji: '' },
    { spanish: 'dificil', furigana: 'むずかしい', kanji: '' },
    { spanish: 'facil', english: 'easy, kind', furigana: 'やさしい', kanji: '' },
    { spanish: 'caliente', english: 'hot', furigana: 'あつい', kanji: '' },
    { spanish: 'frio (de clima)', furigana: 'さむい', kanji: '' },
    { spanish: 'frio (tangible)', furigana: 'つめたい', kanji: '' },
    { spanish: 'largo (tiempo y espacio)', furigana: 'ながい', kanji: '長い' },
    { spanish: 'corto (tiempo y espacio)', english: 'short', furigana: 'みじかい', kanji: '' },
    { spanish: 'divertido', furigana: 'たのしい', kanji: '' },
    { spanish: 'aburrido', furigana: 'つまらない', kanji: '' },
    { spanish: 'interesante', furigana: 'おもしろい', kanji: '' },
    { spanish: 'hermoso (hombres)', english: 'handson', furigana: 'ハンサムな', kanji: '' },
    { spanish: 'hermoso o limpio (mujeres, paisajes, lugares)', furigana: 'きれいな', kanji: '' },
    { spanish: 'comodo, practico', furigana: 'べんりな', kanji: '' },
    { spanish: 'incomodo, impractico', furigana: 'ふべんな', kanji: '' },
    { spanish: 'amable', furigana: 'しんせつな', kanji: '' },
    { spanish: 'importante, vital', furigana: 'だいじな', kanji: '' },
    { spanish: 'tener tiempo libre, estar libre, no tener nada q hacer, estar al pedo', furigana: 'ひまな', kanji: '' },
    { spanish: 'saludable, que tiene mucha energia', furigana: 'げんきな', kanji: '' },
    { spanish: 'con sueño', english: 'sleepy', furigana: 'ねむい', kanji: '' },
    { spanish: 'adorable, lindo', furigana: 'すてきな', kanji: '' },
    { spanish: 'nuevo', furigana: 'あたらしい', kanji: '' },
    { spanish: 'viejo', furigana: 'ふるい', kanji: '' },
    { spanish: 'malo', furigana: 'わるい', kanji: '' },
    { spanish: 'barato', furigana: 'やすい', kanji: '' },
    { spanish: 'caro', furigana: 'たかい', kanji: '' },
    { spanish: 'bajo', furigana: 'ひくい', kanji: '' },
    { spanish: 'ocupado', furigana: 'いそがしい', kanji: '' },
    { spanish: 'bullilloso, lugar con vida', english: 'busy', furigana: 'にぎやか', kanji: '' },
    { spanish: 'bueno, bien', furigana: 'いい', kanji: '' },
    { english: 'near', furigana: 'ちかい', kanji: '' },
    { english: 'far', furigana: 'とおい', kanji: '' },
    { english: 'heavy', furigana: 'おもい' },
    { english: 'light', furigana: 'かるい' },
    { english: 'bright, light', furigana: 'あかるい' },
    { english: 'dark', furigana: 'くらい' },
    { english: 'dangerous', furigana: 'あぶない' },
    { english: 'wide, spacious', furigana: 'ひろい' },
    { english: 'narrow', furigana: 'せまい' },
    { english: 'hot, spicy', furigana: 'からい' },
    { english: 'noisy', furigana: 'うるさい' },
    { english: 'strong', furigana: 'つよい' },
    { english: 'weak', furigana: 'よわい' },
    { english: 'many, a lot', furigana: 'おおい' },
    { english: 'few, a little', furigana: 'すくない' },
    { english: 'lovely, cute', furigana: 'かわいい' },
    { english: 'painful', furigana: 'いたい' },
    { english: 'happy, glad', furigana: 'うれしい' },
    { english: 'sad', furigana: 'かなしい' },
    { english: 'young', furigana: 'わかい' },
    { english: 'fast, early', furigana: 'はやい' },
    { english: 'slow, late', furigana: 'おそい' },
    // { module: '', spanish: '',  furigana: '', kanji: '' },
    // { module: '', spanish: '',  furigana: '', kanji: '' },
    // { module: '', spanish: '',  furigana: '', kanji: '' },
    // { module: '', spanish: '',  furigana: '', kanji: '' },
    // { module: '', spanish: '',  furigana: '', kanji: '' },
    // { module: '', spanish: '',  furigana: '', kanji: '' },
    // { module: '', spanish: '',  furigana: '', kanji: '' },
  ],
  colors: [
    { english: 'color', furigana: 'いろ', kanji: '色' },
    { english: 'orange', furigana: 'オレンジ', kanji: '' },
    { english: 'yellow', furigana: 'きいろ', kanji: '黄色' },
    { english: 'blue', furigana: 'あお', kanji: '青' },
    { english: 'red', furigana: 'あか', kanji: '赤' },
    { english: 'green', furigana: 'みどり', kanji: '緑' },
    { english: 'black', furigana: 'くろ', kanji: '黒' },
    { english: 'brown', furigana: 'ちゃいろ', kanji: '茶色' },
    { english: 'pink', furigana: 'ピンク', kanji: '' },
    { english: 'purple', furigana: 'むらさき', kanji: '紫' },
    { english: 'white', furigana: 'しろ', kanji: '白' },
    { english: 'gray', furigana: 'はいいろ', kanji: '灰色' },
    { english: 'gold', furigana: 'きんいろ', kanji: '金色' },
    { english: 'silver', furigana: 'ぎんいろ', kanji: '銀色' },
    // { spanish: '', furigana: '', kanji: '' },
    // { spanish: '', furigana: '', kanji: '' },
  ],
  counters: [
    { module: 'general', spanish: 'numero 100', furigana: 'ひゃく', kanji: '百' },
    { module: 'general', spanish: 'numero 1000', furigana: 'せん', kanji: '千' },
    { module: 'general', spanish: 'numero 10000', furigana: 'いちまん', kanji: '一万' },
    { module: 'general', spanish: '1 cosas general', furigana: 'ひとつ', kanji: '一つ' },
    { module: 'general', spanish: '2 cosas general', furigana: 'ふたつ', kanji: '二つ' },
    { module: 'general', spanish: '3 cosas general', furigana: 'みっつ', kanji: '三つ' },
    { module: 'general', spanish: '4 cosas general', furigana: 'よっつ', kanji: '四つ' },
    { module: 'general', spanish: '5 cosas general', furigana: 'いつつ', kanji: '五つ' },
    { module: 'general', spanish: '6 cosas general', furigana: 'むっつ', kanji: '六つ' },
    { module: 'general', spanish: '7 cosas general', furigana: 'ななつ', kanji: '七つ' },
    { module: 'general', spanish: '8 cosas general', furigana: 'やっつ', kanji: '八つ' },
    { module: 'general', spanish: '9 cosas general', furigana: 'ここのつ', kanji: '九つ' },
    { module: 'general', spanish: '10 cosas general', furigana: 'とお', kanji: '十つ' },
    { module: 'personas', spanish: '1 personas', furigana: 'ひとり', kanji: '一人' },
    { module: 'personas', spanish: '2 personas', furigana: 'ふたり', kanji: '二人' },
    { module: 'personas', spanish: '3 personas', furigana: 'さんにん', kanji: '三人' },
    { module: 'personas', spanish: '4 personas', furigana: 'よにん', kanji: '四人' },
    { module: 'personas', spanish: '5 personas', furigana: 'ごにん', kanji: '五人' },
    { module: 'personas', spanish: '6 personas', furigana: 'ろくにん', kanji: '六人' },
    { module: 'personas', spanish: '7 personas', furigana: 'しちにん/ななにん', kanji: '七人' },
    { module: 'personas', spanish: '8 personas', furigana: 'はちにん', kanji: '八人' },
    { module: 'personas', spanish: '9 personas', furigana: 'くにん/きゅうにん', kanji: '九人' },
    { module: 'personas', spanish: '10 personas', furigana: 'じゅうにん', kanji: '十人' },
    { module: 'personas', spanish: '11 personas', furigana: 'じゅういちにん', kanji: '十一人' },
    { module: 'personas', spanish: '12 personas', furigana: 'じゅうににん', kanji: '十二人' },
    { module: 'personas', spanish: '14 personas', furigana: 'じゅうよにん', kanji: '十四人' },
    { module: 'personas', spanish: '20 personas', furigana: 'にじゅうににん', kanji: '二十人' },
    { module: 'personas', spanish: '24 personas', furigana: 'にじゅうよにん', kanji: '二十四人' },
    { module: 'personas', spanish: '100 personas', furigana: 'ひゃくにん', kanji: '百人' },
    { module: 'personas', spanish: '1000 personas', furigana: 'せんにん', kanji: '千人' },
    { module: 'personas', spanish: '10000 personas', furigana: 'いちまんにん', kanji: '一万人' },
    { module: 'personas', english: 'how many people', furigana: 'なんにん', kanji: '何人' },
    { module: 'libros', spanish: '1 libros', furigana: 'いっさつ', kanji: '一冊' },
    { module: 'libros', spanish: '2 libros', furigana: 'にさつ', kanji: '二冊' },
    { module: 'libros', spanish: '3 libros', furigana: 'さんさつ', kanji: '三冊' },
    { module: 'libros', spanish: '4 libros', furigana: 'よんさつ', kanji: '四冊' },
    { module: 'libros', spanish: '5 libros', furigana: 'ごさつ', kanji: '五冊' },
    { module: 'libros', spanish: '6 libros', furigana: 'ろくさつ', kanji: '六冊' },
    { module: 'libros', spanish: '7 libros', furigana: 'ななさつ (しちさつ)', kanji: '七冊' },
    { module: 'libros', spanish: '8 libros', furigana: 'はちさつ/はっさつ', kanji: '八冊' },
    { module: 'libros', spanish: '9 libros', furigana: 'きゅうさつ', kanji: '九冊' },
    { module: 'libros', spanish: '10 libros', furigana: 'じゅっさつ/じっさつ', kanji: '十冊' },
    { module: 'libros', spanish: '11 libros', furigana: 'じゅういっさつ', kanji: '十一冊' },
    { module: 'libros', spanish: '12 libros', furigana: 'じゅうにさつ', kanji: '十二冊' },
    { module: 'libros', spanish: '100 libros', furigana: 'ひゃくさつ', kanji: '百冊' },
    { module: 'libros', spanish: '1000 libros', furigana: 'せんさつ', kanji: '千冊' },
    { module: 'libros', spanish: '10000 libros', furigana: 'いちまんさつ', kanji: '一万冊' },
    { module: 'libros', english: 'how many books', furigana: 'なんさつ', kanji: '何冊' },
    {
      module: 'objetos alargados y cilindricos',
      spanish: '1 objetos alargados y cilindricos',
      furigana: 'いっぽん',
      kanji: '一本',
    },
    {
      module: 'objetos alargados y cilindricos',
      spanish: '2 objetos alargados y cilindricos',
      furigana: 'にほん',
      kanji: '二本',
    },
    {
      module: 'objetos alargados y cilindricos',
      spanish: '3 objetos alargados y cilindricos',
      furigana: 'さんぼん',
      kanji: '三本',
    },
    {
      module: 'objetos alargados y cilindricos',
      spanish: '4 objetos alargados y cilindricos',
      furigana: 'よんほん',
      kanji: '四本',
    },
    {
      module: 'objetos alargados y cilindricos',
      spanish: '5 objetos alargados y cilindricos',
      furigana: 'ごほん',
      kanji: '五本',
    },
    {
      module: 'objetos alargados y cilindricos',
      spanish: '6 objetos alargados y cilindricos',
      furigana: 'ろっぽん',
      kanji: '六本',
    },
    {
      module: 'objetos alargados y cilindricos',
      spanish: '7 objetos alargados y cilindricos',
      furigana: 'ななほん (しちほん)',
      kanji: '七本',
    },
    {
      module: 'objetos alargados y cilindricos',
      spanish: '8 objetos alargados y cilindricos',
      furigana: 'はちほん/はっぽん',
      kanji: '八本',
    },
    {
      module: 'objetos alargados y cilindricos',
      spanish: '9 objetos alargados y cilindricos',
      furigana: 'きゅうほん',
      kanji: '九本',
    },
    {
      module: 'objetos alargados y cilindricos',
      spanish: '10 objetos alargados y cilindricos',
      furigana: 'じゅっぽん (じっぽん)',
      kanji: '十本',
    },
    {
      module: 'objetos alargados y cilindricos',
      spanish: '11 objetos alargados y cilindricos',
      furigana: 'じゅういっぽん',
      kanji: '十一本',
    },
    {
      module: 'objetos alargados y cilindricos',
      spanish: '12 objetos alargados y cilindricos',
      furigana: 'じゅうにほん',
      kanji: '十二本',
    },
    {
      module: 'objetos alargados y cilindricos',
      spanish: '100 objetos alargados y cilindricos',
      furigana: 'ひゃっぽん/ひゃくほん',
      kanji: '百本',
    },
    {
      module: 'objetos alargados y cilindricos',
      spanish: '1000 objetos alargados y cilindricos',
      furigana: 'せんぼん',
      kanji: '千本',
    },
    {
      module: 'objetos alargados y cilindricos',
      spanish: '10000 objetos alargados y cilindricos',
      furigana: 'いちまんぼん',
      kanji: '一万本',
    },
    {
      module: 'objetos alargados y cilindricos',
      english: 'how many long/skinny things',
      furigana: 'なんぼん (なんほん) (なんぽん)',
      kanji: '何本',
    },
    { spanish: '1 cosas pequeñas', furigana: 'いっこ', kanji: '一個' },
    { spanish: '2 cosas pequeñas', furigana: 'にこ', kanji: '二個' },
    { spanish: '3 cosas pequeñas', furigana: 'さんこ', kanji: '三個' },
    { spanish: '4 cosas pequeñas', furigana: 'よんこ', kanji: '四個' },
    { spanish: '5 cosas pequeñas', furigana: 'ごこ', kanji: '五個' },
    { spanish: '6 cosas pequeñas', furigana: 'ろっこ', kanji: '六個' },
    { spanish: '7 cosas pequeñas', furigana: 'ななこ (しちこ)', kanji: '七個' },
    { spanish: '8 cosas pequeñas', furigana: 'はちこ/はっこ', kanji: '八個' },
    { spanish: '9 cosas pequeñas', furigana: 'きゅうこ', kanji: '九個' },
    { spanish: '10 cosas pequeñas', furigana: 'じゅっこ (じっこ)', kanji: '十個' },
    { spanish: '11 cosas pequeñas', furigana: 'じゅういっこ', kanji: '十一個' },
    { spanish: '12 cosas pequeñas', furigana: 'じゅうにこ', kanji: '十二個' },
    { spanish: '100 cosas pequeñas', furigana: 'ひゃっこ', kanji: '百個' },
    { spanish: '1,000 cosas pequeñas', furigana: 'せんこ', kanji: '千個' },
    { spanish: '10,000 cosas pequeñas', furigana: 'いちまんこ', kanji: '一万個' },
    { english: 'How many small objects', furigana: 'なんこ', kanji: '何個' },
    { spanish: '1 objetos planos', furigana: 'いちまい', kanji: '一枚' },
    { spanish: '2 objetos planos', furigana: 'にまい', kanji: '二枚' },
    { spanish: '3 objetos planos', furigana: 'さんまい', kanji: '三枚' },
    { spanish: '4 objetos planos', furigana: 'よんまい', kanji: '四枚' },
    { spanish: '5 objetos planos', furigana: 'ごまい', kanji: '五枚' },
    { spanish: '6 objetos planos', furigana: 'ろくまい', kanji: '六枚' },
    { spanish: '7 objetos planos', furigana: 'ななまい (しちまい)', kanji: '七枚' },
    { spanish: '8 objetos planos', furigana: 'はちまい', kanji: '八枚' },
    { spanish: '9 objetos planos', furigana: 'きゅうまい', kanji: '九枚' },
    { spanish: '10 objetos planos', furigana: 'じゅうまい', kanji: '十枚' },
    { spanish: '11 objetos planos', furigana: 'じゅういちまい', kanji: '十一枚' },
    { spanish: '12 objetos planos', furigana: 'じゅうにまい', kanji: '十二枚' },
    { spanish: '100 objetos planos', furigana: 'ひゃくまい', kanji: '百枚' },
    { spanish: '1,000 objetos planos', furigana: 'せんまい', kanji: '千枚' },
    { spanish: '10,000 objetos planos', furigana: 'いちまんまい', kanji: '一万枚' },
    { english: 'how many flatten objects', furigana: 'なんまい', kanji: '何枚' },
    { spanish: '1 animales pequeños', furigana: 'いっぴき', kanji: '一匹' },
    { spanish: '2 animales pequeños', furigana: 'にひき', kanji: '二匹' },
    { spanish: '3 animales pequeños', furigana: 'さんびき', kanji: '三匹' },
    { spanish: '4 animales pequeños', furigana: 'よんひき', kanji: '四匹' },
    { spanish: '5 animales pequeños', furigana: 'ごひき', kanji: '五匹' },
    { spanish: '6 animales pequeños', furigana: 'ろっぴき', kanji: '六匹' },
    { spanish: '7 animales pequeños', furigana: 'ななひき (しちひき)', kanji: '七匹' },
    { spanish: '8 animales pequeños', furigana: 'はちひき/はっぴき', kanji: '八匹' },
    { spanish: '9 animales pequeños', furigana: 'きゅうひき', kanji: '九匹' },
    { spanish: '10 animales pequeños', furigana: 'じゅっぴき (じっぴき)', kanji: '十匹' },
    { spanish: '11 animales pequeños', furigana: 'じゅういっぴき', kanji: '十一匹' },
    { spanish: '12 animales pequeños', furigana: 'じゅうにひき', kanji: '十二匹' },
    { spanish: '100 animales pequeños', furigana: 'ひゃっぴき', kanji: '百匹' },
    { spanish: '1,000 animales pequeños', furigana: 'せんびき', kanji: '千匹' },
    { spanish: '10,000 animales pequeños', furigana: 'いちまんびき', kanji: '一万匹' },
    { english: 'How many small animals', furigana: 'なんびき', kanji: '何匹' },
    { spanish: '1 animales grandes', furigana: 'いっとう', kanji: '一頭' },
    { spanish: '2 animales grandes', furigana: 'にとう', kanji: '二頭' },
    { spanish: '3 animales grandes', furigana: 'さんとう', kanji: '三頭' },
    { spanish: '4 animales grandes', furigana: 'よんとう', kanji: '四頭' },
    { spanish: '5 animales grandes', furigana: 'ごとう', kanji: '五頭' },
    { spanish: '6 animales grandes', furigana: 'ろくとう', kanji: '六頭' },
    { spanish: '7 animales grandes', furigana: 'ななとう (しちとう)', kanji: '七頭' },
    { spanish: '8 animales grandes', furigana: 'はちとう/はっとう', kanji: '八頭' },
    { spanish: '9 animales grandes', furigana: 'きゅうとう', kanji: '九頭' },
    { spanish: '10 animales grandes', furigana: 'じゅっとう/じっとう', kanji: '十頭' },
    { spanish: '11 animales grandes', furigana: 'じゅういっとう', kanji: '十一頭' },
    { spanish: '12 animales grandes', furigana: 'じゅうにとう', kanji: '十二頭' },
    { spanish: '100 animales grandes', furigana: 'ひゃくとう', kanji: '百頭' },
    { spanish: '1,000 animales grandes', furigana: 'せんとう', kanji: '千頭' },
    { spanish: '10,000 animales grandes', furigana: 'いちまんとう', kanji: '一万頭' },
    { english: 'how many big animals', furigana: 'なんとう', kanji: '何頭' },
    { spanish: '1 pajaros', furigana: 'いちわ', kanji: '一羽' },
    { spanish: '2 pajaros', furigana: 'にわ', kanji: '二羽' },
    { spanish: '3 pajaros', furigana: 'さんわ/さんば', kanji: '三羽' },
    { spanish: '4 pajaros', furigana: 'よんわ/よんば (よわ)', kanji: '四羽' },
    { spanish: '5 pajaros', furigana: 'ごわ', kanji: '五羽' },
    { spanish: '6 pajaros', furigana: 'ろくわ (ろっぱ)', kanji: '六羽' },
    { spanish: '7 pajaros', furigana: 'ななわ (しちわ)', kanji: '七羽' },
    { spanish: '8 pajaros', furigana: 'はちわ (はっぱ)', kanji: '八羽' },
    { spanish: '9 pajaros', furigana: 'きゅうわ', kanji: '九羽' },
    { spanish: '10 pajaros', furigana: 'じゅうわ/じゅっぱ (じっぱ)', kanji: '十羽' },
    { spanish: '11 pajaros', furigana: 'じゅういちわ', kanji: '十一羽' },
    { spanish: '12 pajaros', furigana: 'じゅうにわ', kanji: '十二羽' },
    { spanish: '100 pajaros', furigana: 'ひゃくわ/ひゃっぱ', kanji: '百羽' },
    { spanish: '1,000 pajaros', furigana: 'せんわ/せんば', kanji: '千羽' },
    { spanish: '10,000 pajaros', furigana: 'いちまんわ/いちまんば', kanji: '一万羽' },
    { english: 'how many birds', furigana: 'なんわ/なんば', kanji: '何羽' },
    { spanish: '1 maquinas/muebles', furigana: 'いちだい', kanji: '一台' },
    { spanish: '2 maquinas/muebles', furigana: 'にだい', kanji: '二台' },
    { spanish: '3 maquinas/muebles', furigana: 'さんだい', kanji: '三台' },
    { spanish: '4 maquinas/muebles', furigana: 'よんだい', kanji: '四台' },
    { spanish: '5 maquinas/muebles', furigana: 'ごだい', kanji: '五台' },
    { spanish: '6 maquinas/muebles', furigana: 'ろくだい', kanji: '六台' },
    { spanish: '7 maquinas/muebles', furigana: 'ななだい (しちだい)', kanji: '七台' },
    { spanish: '8 maquinas/muebles', furigana: 'はちだい', kanji: '八台' },
    { spanish: '9 maquinas/muebles', furigana: 'きゅうだい', kanji: '九台' },
    { spanish: '10 maquinas/muebles', furigana: 'じゅうだい', kanji: '十台' },
    { spanish: '11 maquinas/muebles', furigana: 'じゅういちだい', kanji: '十一台' },
    { spanish: '12 maquinas/muebles', furigana: 'じゅうにだい', kanji: '十二台' },
    { spanish: '100 maquinas/muebles', furigana: 'ひゃくだい', kanji: '百台' },
    { spanish: '1,000 maquinas/muebles', furigana: 'せんだい', kanji: '千台' },
    { spanish: '10,000 maquinas/muebles', furigana: 'いちまんだい', kanji: '一万台' },
    { english: 'how many machines and furniture', furigana: 'なんだい', kanji: '何台' },
    { spanish: '1 minutos', furigana: 'いっぷん', kanji: '一分' },
    { spanish: '2 minutos', furigana: 'にふん', kanji: '二分' },
    { spanish: '3 minutos', furigana: 'さんぷん/さんふん', kanji: '三分' },
    { spanish: '4 minutos', furigana: 'よんぷん/よんふん', kanji: '四分' },
    { spanish: '5 minutos', furigana: 'ごふん', kanji: '五分' },
    { spanish: '6 minutos', furigana: 'ろっぷん', kanji: '六分' },
    { spanish: '7 minutos', furigana: 'ななふん (しちふん)', kanji: '七分' },
    { spanish: '8 minutos', furigana: 'はっぷん/はちふん', kanji: '八分' },
    { spanish: '9 minutos', furigana: 'きゅうふん', kanji: '九分' },
    { spanish: '10 minutos', furigana: 'じゅっぷん (じっぷん)', kanji: '十分' },
    { spanish: '11 minutos', furigana: 'じゅういっぷん', kanji: '十一分' },
    { spanish: '12 minutos', furigana: 'じゅうにふん', kanji: '十二分' },
    { spanish: '100 minutos', furigana: 'ひゃっぷん', kanji: '百分' },
    { spanish: '1,000 minutos', furigana: 'せんぷん/せんふん', kanji: '千分' },
    { spanish: '10,000 minutos', furigana: 'いちまんぷん/いちまんふん', kanji: '一万分' },
    { english: 'How many minutes', furigana: 'なんぷん/なんふん', kanji: '何分' },
    { spanish: '1 días', furigana: 'いちにち (ついたち/いっぴ)', kanji: '一日' },
    { spanish: '2 días', furigana: 'ふつか', kanji: '二日' },
    { spanish: '3 días', furigana: 'みっか', kanji: '三日' },
    { spanish: '4 días', furigana: 'よっか', kanji: '四日' },
    { spanish: '5 días', furigana: 'いつか', kanji: '五日' },
    { spanish: '6 días', furigana: 'むいか', kanji: '六日' },
    { spanish: '7 días', furigana: 'なのか', kanji: '七日' },
    { spanish: '8 días', furigana: 'ようか', kanji: '八日' },
    { spanish: '9 días', furigana: 'ここのか', kanji: '九日' },
    { spanish: '10 días', furigana: 'とおか', kanji: '十日' },
    { spanish: '11 días', furigana: 'じゅういちにち', kanji: '十一日' },
    { spanish: '12 días', furigana: 'じゅうににち', kanji: '十二日' },
    { spanish: '13 días', furigana: 'じゅうさんにち', kanji: '十三日' },
    { spanish: '14 días', furigana: 'じゅうよっか/じゅうよんにち', kanji: '十四日' },
    { spanish: '15 días', furigana: 'じゅうごにち', kanji: '十五日' },
    { spanish: '16 días', furigana: 'じゅうろくにち', kanji: '十六日' },
    { spanish: '17 días', furigana: 'じゅうしちにち/じゅうななにち', kanji: '十七日' },
    { spanish: '18 días', furigana: 'じゅうはちにち', kanji: '十八日' },
    { spanish: '19 días', furigana: 'じゅうくにち', kanji: '十九日' },
    { spanish: '20 días', furigana: 'はつか (にじゅうにち)', kanji: '二十日' },
    { spanish: '49 días', furigana: 'よんじゅうくにち (しじゅうくにち)', kanji: '四十九日' },
    { spanish: '100 días', furigana: 'ひゃくにち', kanji: '百日' },
    { spanish: '1,000 días', furigana: 'せんにち', kanji: '千日' },
    { spanish: '10,000 días', furigana: 'いちまんにち', kanji: '一万日' },
    { english: 'how many days/which day', furigana: 'なんにち', kanji: '何日' },
    { spanish: '1 frecuencia, la cant de veces q algo sucede', furigana: 'いっかい', kanji: '一回' },
    { spanish: '2 frecuencia, la cant de veces q algo sucede', furigana: 'にかい', kanji: '二回' },
    { spanish: '3 frecuencia, la cant de veces q algo sucede', furigana: 'さんかい', kanji: '三回' },
    { spanish: '4 frecuencia, la cant de veces q algo sucede', furigana: 'よんかい', kanji: '四回' },
    { spanish: '5 frecuencia, la cant de veces q algo sucede', furigana: 'ごかい', kanji: '五回' },
    { spanish: '6 frecuencia, la cant de veces q algo sucede', furigana: 'ろっかい', kanji: '六回' },
    {
      spanish: '7 frecuencia, la cant de veces q algo sucede',
      furigana: 'ななかい (しちかい)',
      kanji: '七回',
    },
    { spanish: '8 frecuencia, la cant de veces q algo sucede', furigana: 'はちかい/はっかい', kanji: '八回' },
    { spanish: '9 frecuencia, la cant de veces q algo sucede', furigana: 'きゅうかい', kanji: '九回' },
    {
      spanish: '10 frecuencia, la cant de veces q algo sucede',
      furigana: 'じゅっかい/じっかい',
      kanji: '十回',
    },
    { spanish: '11 frecuencia, la cant de veces q algo sucede', furigana: 'じゅういっかい', kanji: '十一回' },
    { spanish: '12 frecuencia, la cant de veces q algo sucede', furigana: 'じゅうにかい', kanji: '十二回' },
    { spanish: '100 frecuencia, la cant de veces q algo sucede', furigana: 'ひゃっかい', kanji: '百回' },
    { spanish: '1,000 frecuencia, la cant de veces q algo sucede', furigana: 'せんかい', kanji: '千回' },
    {
      spanish: '10,000 frecuencia, la cant de veces q algo sucede',
      furigana: 'いちまんかい',
      kanji: '一万回',
    },
    { english: 'How many frecuency/amount of times something happens', furigana: 'なんかい', kanji: '何回' },
    // { spanish: '', furigana: '', kanji: '' },
    // { spanish: '', furigana: '', kanji: '' },
    // { spanish: '', furigana: '', kanji: '' },
  ],
};

export default words;
